[workspace]
authors = ["Noah Jutz <noah@noahjutz.com>"]
channels = ["conda-forge", "robostack-humble"]
name = "pixi_threadpoolbuilderror"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
ros-humble-ros2run = ">=0.18.12,<0.19"
